[[redirects]]
  from = "/bio_anna-jones.html"
  to = "/"
  from = "/bio_brian-chung.html
  to = "/"
  from = "/bio_debra-jaff.html
  to = "/"
  from = "/bio_erin-lacey.html
  to = "/"
  from = "/bio_gail-hadley.html
  to = "/"
  from = "/bio_ido-weinberg.html
  to = "/"
  from = "/bio_justin-mcneil.html
  to = "/"
  from = "/bio_justin-thompson.html
  to = "/"
  from = "/bio_kathryn-lane.html
  to = "/"
  from = "/bio_lindsey-st-louis.html
  to = "/"
  from = "/bio_luis-cintron.html
  to = "/"
  from = "/bio_meghna-lahiry.html
  to = "/"
  from = "/bio_michael-jaff.html
  to = "/"
  from = "/bio_noelle-saulnier.html
  to = "/"
  from = "/bio_ritu-shrestha.html
  to = "/"
  from = "/bio_sabina-dhami.html
  to = "/"
  from = "/bio_sandra-croteau.html
  to = "/"
  from = "/bio_victoria-sova.html
  to = "/"
  from = "/casestudy1_image1.html
  to = "/"
  from = "/casestudy1_image2.html
  to = "/"
  from = "/casestudy2_image1.html
  to = "/"
  from = "/casestudy3_image1.html
  to = "/"
  from = "/casestudy3_image2.html
  to = "/"
  from = "/casestudy4_image1.html
  to = "/"
  from = "/casestudy4_image1.html
  to = "/"
  from = "/casestudy5_image1.html
  to = "/"