[[redirects]]
  from = "/bio_anna-jones.html"
  to = "/
  force = true

[[redirects]]
  from = "/bio_brian-chung.html"
  to = "/
  force = true

[[redirects]]
  from = "/bio_debra-jaff.html"
  to = "/
  force = true

[[redirects]]
  from = "/bio_erin-lacey.html"
  to = "/
  force = true

[[redirects]]
  from = "/bio_gail-hadley.html"
  to = "/
  force = true

[[redirects]]
  from = "/bio_ido-weinberg.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_justin-mcneil.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_justin-thompson.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_kathryn-lane.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_lindsey-st-louis.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_luis-cintron.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_meghna-lahiry.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_michael-jaff.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_noelle-saulnier.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_ritu-shrestha.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_sabina-dhami.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_sandra-croteau.html"
  to = "/"
  force = true

[[redirects]]
  from = "/bio_victoria-sova.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy1_image1.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy1_image2.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy2_image1.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy3_image1.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy3_image2.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy4_image1.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy4_image1.html"
  to = "/"
  force = true

[[redirects]]
  from = "/casestudy5_image1.html"
  to = "/"
  force = true